name: Docs
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up our JDK environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build Dokka HTML
        run: ./gradlew dokkaHtmlMultiModule
      - name: Setup docs folder
        run: |
          mkdir -p build/docs
          mkdir -p build/docs/api
          echo "makth.dev" > build/docs/CNAME
          cp -r build/dokka/htmlMultiModule/* build/docs/api
          cp -r docs/* build/docs
      - name: Generate sitemap
        uses: guimauvedigital/generate-sitemap@v1
        with:
          base_url: https://makth.dev
          output_path: build/docs/sitemap.xml
          input_dir: build/docs
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: build/docs
          destination: build/docs/_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/_site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
