name: Docs
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up our JDK environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build Dokka HTML
        run: ./gradlew dokkaHtmlMultiModule
      - name: Setup docs folder
        run: |
          mkdir -p build/docs
          mkdir -p build/docs/api
          cp -r build/dokka/htmlMultiModule/* build/docs/api
          cp -r docs/* build/docs
          echo 'makth.dev' > build/docs/CNAME
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs
          publish_branch: gh-pages
